=begin
#Route Optimization API

#Our Route Optimization API solves the so called vehicle routing problem fast. It calculates an optimal tour for a set of vehicles, services and constraints

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'

# Unit tests for GraphHopper::VrpApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'VrpApi' do
  before do
    # run before each test
    @instance = GraphHopper::VrpApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of VrpApi' do
    it 'should create an instact of VrpApi' do
      expect(@instance).to be_instance_of(GraphHopper::VrpApi)
    end
  end

  # unit tests for post_vrp
  # Solves vehicle routing problems
  # This endpoint for solving vehicle routing problems, i.e. traveling salesman or vehicle routing problems, and returns the solution. 
  # @param key your API key
  # @param body Request object that contains the problem to be solved
  # @param [Hash] opts the optional parameters
  # @return [JobId]
  describe 'post_vrp test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
