=begin
#Route Optimization API

#Our Route Optimization API solves the so called vehicle routing problem fast. It calculates an optimal tour for a set of vehicles, services and constraints

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

# Common files
require 'graphhopper/api_client'
require 'graphhopper/api_error'
require 'graphhopper/version'
require 'graphhopper/configuration'

# Models
require 'graphhopper/models/activity'
require 'graphhopper/models/address'
require 'graphhopper/models/algorithm'
require 'graphhopper/models/cost_matrix'
require 'graphhopper/models/job_id'
require 'graphhopper/models/model_break'
require 'graphhopper/models/objective'
require 'graphhopper/models/relation'
require 'graphhopper/models/request'
require 'graphhopper/models/response'
require 'graphhopper/models/route'
require 'graphhopper/models/service'
require 'graphhopper/models/shipment'
require 'graphhopper/models/solution'
require 'graphhopper/models/solution_unassigned'
require 'graphhopper/models/stop'
require 'graphhopper/models/time_window'
require 'graphhopper/models/vehicle'
require 'graphhopper/models/vehicle_type'

# APIs
require 'graphhopper/api/solution_api'
require 'graphhopper/api/vrp_api'

module GraphHopper
  class << self
    # Customize default settings for the SDK using block.
    #   GraphHopper.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
